# Generated by Django 4.1.3 on 2022-12-01 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('academy_name', models.CharField(max_length=100)),
                ('academy_description', models.TextField()),
                ('featured_video_link', models.CharField(max_length=1000)),
                ('staff_count', models.IntegerField(default=12)),
                ('student_count', models.IntegerField(default=239)),
                ('courses_count', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_duration', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=300)),
                ('course_description', models.TextField()),
                ('course_image', models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='courses/')),
                ('course_seat_available', models.IntegerField(default=10)),
                ('course_duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.courseduration')),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('faculty_name', models.CharField(max_length=200)),
                ('faculty_image', models.ImageField(blank=True, default='default/faculty.jpg', null=True, upload_to='faculties/')),
                ('faculty_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('poster_image', models.ImageField(upload_to='poster/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSayAboutUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('student_description', models.TextField(max_length=500)),
                ('student_image', models.ImageField(blank=True, default='default/student.jpg', null=True, upload_to='students/')),
                ('student_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='course_faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.faculties'),
        ),
    ]
